export const STATES = {
  INTRO_SEQUENCE: "INTRO_SEQUENCE",
  BOOT: "BOOT",
  INTRO: "INTRO",
  MAIN: "MAIN",
  SECTION_VIEW: "SECTION_VIEW",
  ARTICLE_VIEW: "ARTICLE_VIEW",
  GAME_VIEW: "GAME_VIEW"
};
